version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    networks:
      - ai-recruitment-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Remove the deploy section above if you don't have NVIDIA GPU

  ai-recruitment-app:
    build: .
    container_name: ai-recruitment-app
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=hf.co/Cactus-Compute/Qwen3-1.7B-Instruct-GGUF:Q4_K_M
      - DEBUG=false
      - DOCKER_ENV=true
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ai-recruitment-network

volumes:
  ollama_data:

networks:
  ai-recruitment-network:
    driver: bridge
